

import { CardCharacter, Pagination } from '@/components';
import { getCharacters } from '@/helpers/characterFetcher';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Characters",
  description: "Generated by create next app",
};

interface SeverParams {
  searchParams: {
    page:string;
  }
}
export default async function CharactersPage({searchParams}:SeverParams) {
  let currentPage = 1; 

  if (searchParams.page && !isNaN(Number(searchParams.page))) {
    currentPage = Number(searchParams.page);
  }

  const response = await getCharacters(currentPage);
  const { count, results } = response;
  const totalPages = Math.ceil(count/10)

  return (
    <div>
      <h2 className='font-jedi text-3xl md:text-7xl text-center py-6 text-yellow-300'>Characters</h2>
      <div className="flex items-center justify-center flex-wrap min-h-screen">
        <div className="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-4">
        {
           results.map((character, index) => (
                <CardCharacter character={character} key={index}/>
          ))
        }
        </div>
      </div>
      <div className='flex justify-center'>
        <Pagination totalPages={totalPages}/>
      </div>
    </div>
  );
}