import { Navbar } from '@/components';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
      <div className='container mx-auto px-5'>
      {children}
      </div>
    </>
  );
}
