import { Footer, Navbar } from '@/components';
import type { Metadata } from 'next';
import { Suspense } from 'react';

export const metadata: Metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Navbar />
        <div className='container mx-auto px-5'>
          <Suspense>
            {children}
          </Suspense>
        </div>
      <Footer />
    </>
  );
}
